# Generated by Django 4.0.6 on 2022-11-11 04:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0002_alter_donors_created_by'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hospital_requests',
            new_name='HospitalRequests',
        ),
        migrations.RenameModel(
            old_name='rbc_stock',
            new_name='RbcStock',
        ),
        migrations.AlterField(
            model_name='patients',
            name='hospital',
            field=models.CharField(max_length=100),
        ),
    ]
